[package]
name = "ncnn-sys"
version = "0.1.7"
authors = ["DarkSky"]
edition = "2018"
links = "ncnn"
license-file = "ncnn/LICENSE.txt"
description = "just a ncnn rust unsafe binding"
homepage = "https://github.com/darkskygit/waifu2x.rs"
repository = "https://github.com/darkskygit/waifu2x.rs"
keywords = ["binding", "ncnn"]
exclude = [
    "ncnn/**/*",
    "!ncnn/ncnn/**/*",
    "vulkan/**/*.pdb",
    "**/.git",
    ".gitmodules"
]
readme = "README.md"

[features]
default = ["bundled"]
bundled = []

[build-dependencies]
cmake = "0.1.48"
path-absolutize = "3.0.11"
fs_extra = "1.2.0"
